FROM debian:jessie

EXPOSE 5000
ENTRYPOINT ["/usr/bin/make"]
CMD ["run"]

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
        git locales python3 python3-setuptools
RUN easy_install pip wheel

RUN echo 'en_AU.UTF-8 UTF-8' > /etc/locale.gen && locale-gen && update-locale LANG=en_AU.UTF-8
ENV LANG en_AU.UTF-8

RUN mkdir -p /code/data
WORKDIR /code
ADD Makefile /code/Makefile

ADD work/bower_components /code/bower_components
ADD _collect_static.sh /code/_collect_static.sh
RUN make collectstatic

ADD requirements.txt /code/requirements.txt
ADD test-requirements.txt /code/test-requirements.txt
ADD wheelhouse /code/wheelhouse
RUN make pythondeps

ADD dockci /code/dockci
ADD tests /code/tests
ADD pylint.conf /code/pylint.conf
ADD wsgi.py /code/wsgi.py
