"""GitLab

Revision ID: 104ef30bb0
Revises: 363f5acbbfc
Create Date: 2015-11-02 13:37:12.981344

"""

# revision identifiers, used by Alembic.
revision = '104ef30bb0'
down_revision = '363f5acbbfc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('gitlab_base_uri', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('gitlab_private_token', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('gitlab_repo_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'gitlab_repo_id')
    op.drop_column('project', 'gitlab_private_token')
    op.drop_column('project', 'gitlab_base_uri')
    ### end Alembic commands ###
