"""target registry

Revision ID: 14d12168955
Revises: 239afb414e1
Create Date: 2015-11-13 03:11:20.365162

"""

# revision identifiers, used by Alembic.
revision = '14d12168955'
down_revision = '239afb414e1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('target_registry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'authenticated_registry', ['target_registry_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'target_registry_id')
    ### end Alembic commands ###
