"""branch pattern

Revision ID: 22fef3d92ff
Revises: 4c22f218654
Create Date: 2015-11-17 02:16:40.918465

"""

# revision identifiers, used by Alembic.
revision = '22fef3d92ff'
down_revision = '4c22f218654'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('branch_pattern', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'branch_pattern')
    ### end Alembic commands ###
