"""authenticated registry

Revision ID: 239afb414e1
Revises: 20d5bd63d3d
Create Date: 2015-11-09 05:42:52.339745

"""

# revision identifiers, used by Alembic.
revision = '239afb414e1'
down_revision = '20d5bd63d3d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticated_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('base_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_index(op.f('ix_authenticated_registry_base_name'), 'authenticated_registry', ['base_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authenticated_registry_base_name'), table_name='authenticated_registry')
    op.drop_table('authenticated_registry')
    ### end Alembic commands ###
