"""remove_hipchat

Revision ID: 363f5acbbfc
Revises: 1c398722878
Create Date: 2015-10-26 11:55:07.751505

"""

# revision identifiers, used by Alembic.
revision = '363f5acbbfc'
down_revision = '1c398722878'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'hipchat_api_token')
    op.drop_column('project', 'hipchat_room')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('hipchat_room', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('hipchat_api_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
