"""branch pattern

Revision ID: 3ce0ed6fff6
Revises: 4c22f218654
Create Date: 2015-11-21 14:58:08.419268

"""

# revision identifiers, used by Alembic.
revision = '3ce0ed6fff6'
down_revision = '4c22f218654'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    from dockci.models.db_types import RegexType
    op.add_column('project', sa.Column('branch_pattern', RegexType(), nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'branch_pattern')
    ### end Alembic commands ###
