"""empty message

Revision ID: 42fc9c97277
Revises: 14d12168955
Create Date: 2015-11-15 02:04:07.682044

"""

# revision identifiers, used by Alembic.
revision = '42fc9c97277'
down_revision = '14d12168955'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticated_registry', sa.Column('insecure', sa.Boolean(), nullable=False, server_default='FALSE'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticated_registry', 'insecure')
    ### end Alembic commands ###
