"""empty message

Revision ID: 47229476820
Revises: 42fc9c97277
Create Date: 2015-11-15 02:43:36.828816

"""

# revision identifiers, used by Alembic.
revision = '47229476820'
down_revision = '42fc9c97277'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authenticated_registry', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authenticated_registry', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
