"""authenticated registries

Revision ID: 4c22f218654
Revises: 20d5bd63d3d
Create Date: 2015-11-16 11:17:19.479593

"""

# revision identifiers, used by Alembic.
revision = '4c22f218654'
down_revision = '20d5bd63d3d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticated_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('base_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('insecure', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_index(op.f('ix_authenticated_registry_base_name'), 'authenticated_registry', ['base_name'], unique=True)
    op.add_column('project', sa.Column('target_registry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'authenticated_registry', ['target_registry_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'target_registry_id')
    op.drop_index(op.f('ix_authenticated_registry_base_name'), table_name='authenticated_registry')
    op.drop_table('authenticated_registry')
    ### end Alembic commands ###
