"""add stage success

Revision ID: 553390a1723
Revises: 5773ec3bc06
Create Date: 2016-01-18 06:22:22.634837

"""

# revision identifiers, used by Alembic.
revision = '553390a1723'
down_revision = '5773ec3bc06'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_stage_tmp', sa.Column('success', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_stage_tmp', 'success')
    ### end Alembic commands ###
