"""project

Revision ID: ca6a9d39bb
Revises: 2174921dd1a
Create Date: 2015-08-17 14:49:16.695764

"""

# revision identifiers, used by Alembic.
revision = 'ca6a9d39bb'
down_revision = '2174921dd1a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('utility', sa.Boolean(), nullable=False),
    sa.Column('hipchat_api_token', sa.String(length=255), nullable=True),
    sa.Column('hipchat_room', sa.String(length=255), nullable=True),
    sa.Column('github_repo_id', sa.String(length=255), nullable=True),
    sa.Column('github_hook_id', sa.Integer(), nullable=True),
    sa.Column('github_secret', sa.String(length=255), nullable=True),
    sa.Column('github_auth_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['github_auth_token_id'], ['o_auth_token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=True)
    op.create_index(op.f('ix_project_utility'), 'project', ['utility'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_utility'), table_name='project')
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_table('project')
    ### end Alembic commands ###
