"""job

Revision ID: f8d315a31e
Revises: ca6a9d39bb
Create Date: 2015-08-20 18:56:41.386259

"""

# revision identifiers, used by Alembic.
revision = 'f8d315a31e'
down_revision = 'ca6a9d39bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_ts', sa.DateTime(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('complete_ts', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Enum('success', 'fail', 'broken', name='job_results'), nullable=True),
    sa.Column('repo', sa.Text(), nullable=False),
    sa.Column('commit', sa.String(length=41), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('image_id', sa.String(length=65), nullable=True),
    sa.Column('container_id', sa.String(length=65), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('docker_client_host', sa.Text(), nullable=True),
    sa.Column('git_author_name', sa.Text(), nullable=True),
    sa.Column('git_author_email', sa.Text(), nullable=True),
    sa.Column('git_committer_name', sa.Text(), nullable=True),
    sa.Column('git_committer_email', sa.Text(), nullable=True),
    sa.Column('git_changes', sa.Text(), nullable=True),
    sa.Column('ancestor_job_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_project_id'), 'job', ['project_id'], unique=False)
    op.create_index(op.f('ix_job_result'), 'job', ['result'], unique=False)
    op.create_table('job_stage_tmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=31), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_stage_tmp_job_id'), 'job_stage_tmp', ['job_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_stage_tmp_job_id'), table_name='job_stage_tmp')
    op.drop_table('job_stage_tmp')
    op.drop_index(op.f('ix_job_result'), table_name='job')
    op.drop_index(op.f('ix_job_project_id'), table_name='job')
    op.drop_table('job')
    ### end Alembic commands ###
